apiVersion: apps/v1
kind: Deployment
metadata:
  name: Appache Tomcat
  labels:
    app: Appache Tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Appache Tomcat
  template:
    metadata:
      labels:
        app: Appache Tomcat
    spec:
      containers:
      - name: Appache Tomcat
        image: Appache Tomcat:latest
        ports:
        - containerPort: 80
