apiVersion: v1
kind: Service
metadata:
  name: tomcat-loadbalancer
spec:
  selector:
    app: tomcat       # Label selector to match pods with label "app: nginx"
  ports:
    - protocol: TCP
      port: 8080    # Port on which the service will listen
      targetPort: 8080 # Port on which the pods are listening
  type: LoadBalancer # Type of service - LoadBalancer
